# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Build Faulty Images"

on:
  push:
    branches: [faulty]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_faulty:
    permissions:  # required by the reusable workflow
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/tsuga-component-build-images.yml
    with:
      push: true
      version: faulty
    secrets: inherit
