# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlp_http/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlp_http/example]

exporters:
  otlphttp/tsuga:
    endpoint: ${env:TSUGA_ENDPOINT}
    compression: gzip
    headers:
      Authorization: "Bearer ${env:TSUGA_API_KEY}"

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlphttp/tsuga]
    metrics:
      exporters: [otlphttp/tsuga]
    logs:
      exporters: [otlphttp/tsuga]
